### ISSUE TITLE
bugs in math evaluation

### ISSUE THREAD

**Issue by raphael-sch** [zjunlp/TRICE#2]
there are some bugs in the math evaluation:

this is the code to postprocess answers without calculator usage.
```
            sentences = response.split(".")
            sentences = [s for s in sentences if s != ""]
            pred_sentence = sentences[-1] if len(sentences) > 0 else ""
            pattern = re.compile(r"-?[1-9]\d*")
            pred = pattern.findall(pred_sentence)
            pred = int(pred[-1].replace(",", "")) if len(pred) > 0 else None
```

1. The regex does parse large number with comma incorrectly, e.g. 100,000 as 100. So even if the model produces the correct answer, it would not match against the gold answer. Out of the 1785 dev instances, 14 have a comma in them. 
2. The "pred" number is casted to int such that the model without calculator can never be correct if the gold answer is a float (9/1785).

If the numbers in Table 1 for the Alpaca-LoRA-7B baseline without calculator are computed with this script they are not accurate and should be higher.

EDIT:
Just saw that most of the gold answers with float have a 0 decimal. Only (9/1785) are affected, so the numbers in Table 1 would change only a little.

**Comment by zxlzr** [comment]
Hi, could you provide more details about your issue?

**Comment by raphael-sch** [comment]
> Hi, could you provide more details about your issue?

see edit

**Comment by GoooDte** [comment]
Hello, thank you for your careful analysis and experimentation with our code.
In fact, we did come across the issue you mentioned during the experimental process. However, since the number of answers containing comma-separated numbers or numbers with significant decimals was minimal, we overlooked this aspect. Furthermore, all baselines were evaluated based on this logic, ensuring fairness was not compromised.

We will make the necessary corrections based on your feedback as soon as possible. However, it is indeed a challenging task to achieve perfect transformation from string-based to accurate numbers generated by the language model due to the diversity of number representations. Do you have any suggestions or recommendations to share on how to handle the perfect conversion of string-based numbers?
