### ISSUE TITLE
Training with Llama 3 base model

### ISSUE THREAD

**Issue by lisaalaz** [zjunlp/TRICE#6]
Hi, we would like to include the results of your framework in a paper we are working on, particularly TRICE-SPLIT on GSM8K-XL (similar to GSM8K-Hard) using Llama 3 as the base model. However, so far we have been unable to replicate similar results to yours, and after training both steps the performance reduces compared to the base model with few shot prompting. Have you by any chance tried to apply your framework to Llama 3 and if so could you share the optimal hyperparameters for training? Or do you have any other insight that may help us improve TRICE's performance with this base model? Many thanks!

**Comment by GoooDte** [comment]
Sorry that we have not experimented with Llama3. The models we used in our paper have all been fine-tuned on the Alpaca dataset. We attempted direct fine-tuning on our dataset using the Alpaca format on Llama2, but the performance was poor primarily due to a lack of adherence to the format. Therefore, we might recommend training in the conversational format of Llama3 or first training on the Alpaca dataset.
